//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongViec
    {
        public int ID { get; set; }
        public int ID_LopHocPhan { get; set; }
        public string MoTa { get; set; }
        public double SoGioQuyDoi { get; set; }
        public System.DateTime ThoiHanHoanThanh { get; set; }
        public string NoiLamViec { get; set; }
        public string KetQuaMongDoi { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public string KetQuaCongViec { get; set; }
        public Nullable<int> ID_TaiKhoan { get; set; }
        public string HinhAnhMinhChung { get; set; }
    
        public virtual LopHocPhan LopHocPhan { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
