//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaPhongVan
    {
        public int ID { get; set; }
        public int ID_UngTuyenTroGiang { get; set; }
        public string NgoaiHinhTacPhong { get; set; }
        public string KienThuc { get; set; }
        public string HieuBietCongViec { get; set; }
        public string ThaiDoTichCuc { get; set; }
        public string KyNangTrinhBay { get; set; }
        public string KyNangGiaoTiep { get; set; }
        public string GiaiQuyetVanDe { get; set; }
        public string KhaNangSuPham { get; set; }
        public string KyNangCNTT { get; set; }
        public string YeuToKhac { get; set; }
        public Nullable<int> TongSoDiemDat { get; set; }
        public Nullable<int> TongSoDiemPhanVan { get; set; }
        public Nullable<int> TongSoDiemChuaDat { get; set; }
        public string NhanXet { get; set; }
        public Nullable<bool> KetLuanDat { get; set; }
        public Nullable<System.DateTime> NgayPhongVan { get; set; }
        public Nullable<System.DateTime> NgayDuyet { get; set; }
    
        public virtual UngTuyenTroGiang UngTuyenTroGiang { get; set; }
    }
}
