//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeXuatTroGiang
    {
        public int ID { get; set; }
        public int ID_HocPhan { get; set; }
        public string LyDoDeXuat { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual HocPhan HocPhan { get; set; }
    }
}
