//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemDanh
    {
        public int ID { get; set; }
        public int ID_DanhSachSinhVien { get; set; }
        public Nullable<int> Tuan { get; set; }
        public bool CoMat { get; set; }
    
        public virtual DanhSachSinhVien DanhSachSinhVien { get; set; }
    }
}
