//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormDangKyTroGiang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormDangKyTroGiang()
        {
            this.UngTuyenTroGiang = new HashSet<UngTuyenTroGiang>();
        }
    
        public int ID { get; set; }
        public int ID_HocKy { get; set; }
        public int ID_Nganh { get; set; }
        public System.DateTime ThoiGianMo { get; set; }
        public System.DateTime ThoiGianDong { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual Nganh Nganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UngTuyenTroGiang> UngTuyenTroGiang { get; set; }
    }
}
