//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHocPhan()
        {
            this.CongViec = new HashSet<CongViec>();
            this.DanhSachSinhVien = new HashSet<DanhSachSinhVien>();
            this.DeXuatTroGiang = new HashSet<DeXuatTroGiang>();
            this.LichHoc = new HashSet<LichHoc>();
            this.PhanCongTroGiang = new HashSet<PhanCongTroGiang>();
            this.ThoiKhoaBieu = new HashSet<ThoiKhoaBieu>();
            this.UngTuyenTroGiang = new HashSet<UngTuyenTroGiang>();
        }
    
        public int ID { get; set; }
        public int ID_HocKy { get; set; }
        public int ID_Nganh { get; set; }
        public string MaMH { get; set; }
        public string MaLHP { get; set; }
        public string TenHP { get; set; }
        public string LoaiHP { get; set; }
        public string MaCBGD { get; set; }
        public string TenCBGD { get; set; }
        public Nullable<int> ID_TaiKhoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachSinhVien> DanhSachSinhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeXuatTroGiang> DeXuatTroGiang { get; set; }
        public virtual HocKy HocKy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichHoc> LichHoc { get; set; }
        public virtual Nganh Nganh { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCongTroGiang> PhanCongTroGiang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UngTuyenTroGiang> UngTuyenTroGiang { get; set; }
    }
}
