//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CongTacTroGiangKhoaCNTTEntities : DbContext
    {
        public CongTacTroGiangKhoaCNTTEntities()
            : base("name=CongTacTroGiangKhoaCNTTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CongViec> CongViec { get; set; }
        public virtual DbSet<DanhGiaPhongVan> DanhGiaPhongVan { get; set; }
        public virtual DbSet<DanhSachSinhVien> DanhSachSinhVien { get; set; }
        public virtual DbSet<DeXuatTroGiang> DeXuatTroGiang { get; set; }
        public virtual DbSet<DiemDanh> DiemDanh { get; set; }
        public virtual DbSet<FormDangKyTroGiang> FormDangKyTroGiang { get; set; }
        public virtual DbSet<HocKy> HocKy { get; set; }
        public virtual DbSet<LopHocPhan> LopHocPhan { get; set; }
        public virtual DbSet<Nganh> Nganh { get; set; }
        public virtual DbSet<PhanCongTroGiang> PhanCongTroGiang { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
        public virtual DbSet<ThoiKhoaBieu> ThoiKhoaBieu { get; set; }
        public virtual DbSet<ThongBao> ThongBao { get; set; }
        public virtual DbSet<UngTuyenTroGiang> UngTuyenTroGiang { get; set; }
    }
}
