//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCongTroGiang
    {
        public int ID { get; set; }
        public int ID_LopHocPhan { get; set; }
        public int ID_TaiKhoan { get; set; }
        public bool DaNghiViec { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual LopHocPhan LopHocPhan { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
