//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.CongViec = new HashSet<CongViec>();
            this.FormDangKyTroGiang = new HashSet<FormDangKyTroGiang>();
            this.FormDangKyTroGiang1 = new HashSet<FormDangKyTroGiang>();
            this.LopHocPhan = new HashSet<LopHocPhan>();
            this.PhanCongTroGiang = new HashSet<PhanCongTroGiang>();
            this.ThongBao = new HashSet<ThongBao>();
            this.UngTuyenTroGiang = new HashSet<UngTuyenTroGiang>();
            this.ThongBaoMail = new HashSet<ThongBaoMail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Nganh { get; set; }
        public string ID_AspNetUsers { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public bool TrangThai { get; set; }
        public string Ma { get; set; }
        public string GioiTinh { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SoTaiKhoanNganHang { get; set; }
        public string TenNganHang { get; set; }
        public string ChuTaiKhoanNganHang { get; set; }
        public string MaSoCanCuocCongDan { get; set; }
        public string GhiChu { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<int> ID_Khoa { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormDangKyTroGiang> FormDangKyTroGiang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormDangKyTroGiang> FormDangKyTroGiang1 { get; set; }
        public virtual Khoa Khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LopHocPhan> LopHocPhan { get; set; }
        public virtual Nganh Nganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCongTroGiang> PhanCongTroGiang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UngTuyenTroGiang> UngTuyenTroGiang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBaoMail> ThongBaoMail { get; set; }
    }
}
