//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieu
    {
        public int ID { get; set; }
        public int ID_HocKy { get; set; }
        public int ID_Nganh { get; set; }
        public Nullable<int> ID_LopHocPhan { get; set; }
        public string MaLHP { get; set; }
        public string MaGocLHP { get; set; }
        public string LoaiHP { get; set; }
        public string MaMH { get; set; }
        public string MaLop { get; set; }
        public string TenPhong { get; set; }
        public string PH { get; set; }
        public string PH_X { get; set; }
        public Nullable<int> SucChua { get; set; }
        public Nullable<int> TSMH { get; set; }
        public Nullable<int> SoTietDaXep { get; set; }
        public string Thu { get; set; }
        public Nullable<int> TietBD { get; set; }
        public Nullable<int> SoTiet { get; set; }
        public string TietHoc { get; set; }
        public Nullable<int> SiSoTKB { get; set; }
        public Nullable<int> Trong { get; set; }
        public string TinhTrangLHP { get; set; }
        public string TuanHoc2 { get; set; }
        public Nullable<int> ThuS { get; set; }
        public Nullable<int> TietS { get; set; }
        public Nullable<int> SoSVDK { get; set; }
        public Nullable<int> TuanBD { get; set; }
        public Nullable<int> TuanKT { get; set; }
        public string GhiChu1 { get; set; }
        public string GhiChu2 { get; set; }
        public Nullable<int> ID_TaiKhoan { get; set; }
        public Nullable<int> SoTC { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual LopHocPhan LopHocPhan { get; set; }
        public virtual Nganh Nganh { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
