//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieu
    {
        public int ID { get; set; }
        public int ID_HocKy { get; set; }
        public int ID_Nganh { get; set; }
        public int ID_HocPhan { get; set; }
        public int ID_Phong { get; set; }
        public string MaLHP { get; set; }
        public string MaGocLHP { get; set; }
        public string LoaiHP { get; set; }
        public string MaMH { get; set; }
        public string MaLop { get; set; }
        public int TSMH { get; set; }
        public Nullable<int> SoTietDaXep { get; set; }
        public string Thu { get; set; }
        public int TietBD { get; set; }
        public int SoTiet { get; set; }
        public string TietHoc { get; set; }
        public int SiSoTKB { get; set; }
        public int Trong { get; set; }
        public string TinhTrangLHP { get; set; }
        public string TuanHoc2 { get; set; }
        public int ThuS { get; set; }
        public int TietS { get; set; }
        public int SoSVDK { get; set; }
        public int TuanBD { get; set; }
        public int TuanKT { get; set; }
        public string MaCBGD { get; set; }
        public string TenCBGD { get; set; }
        public string GhiChu1 { get; set; }
        public string GhiChu2 { get; set; }
        public Nullable<int> ID_TaiKhoan { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual HocPhan HocPhan { get; set; }
        public virtual Nganh Nganh { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
