//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string NoIDung { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public Nullable<int> ID_TaiKhoan { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
