//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCongTacTroGiangKhoaCNTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UngTuyenTroGiang
    {
        public int ID { get; set; }
        public int ID_FormDangKyTroGiang { get; set; }
        public int ID_HocPhan { get; set; }
        public int ID_TaiKhoan { get; set; }
        public string MSSV { get; set; }
        public string Email { get; set; }
        public string HoTen { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public decimal DiemTBTL { get; set; }
        public int DiemRL { get; set; }
        public decimal DiemTKMH { get; set; }
        public string HinhAnhMinhChung { get; set; }
        public bool TrangThai { get; set; }
        public string PhongVan { get; set; }
    
        public virtual FormDangKyTroGiang FormDangKyTroGiang { get; set; }
        public virtual HocPhan HocPhan { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
